Geolocation link to data retrieval and country data wrapper
hack4impact/berkman pull request #21
Opened 2016-12-27 00:22 UTC by sknop8

- If there is geolocation data, we make an API call for that respective country and get the data from the Internet Monitor 
- The function getCountryIndicators reorganizes the data for the current country by indicator

2017-01-10 23:06 UTC, rileynwong requested changes

2017-01-10 23:06 UTC, rileynwong commented on RNApp/app/backend/tempBackend.js
> +// Returns a keymap of indicators to arrays of data points
Nit: block comment instead of line comments? `/* */` instead of `//`

2017-01-10 23:06 UTC, rileynwong commented on RNApp/app/backend/tempBackend.js
> +  let indic_data = data['data']['relationships']['data_points']['data'];
Nit: camelCase for variable names, i.e. `indicatorData`

2017-01-10 23:06 UTC, rileynwong commented on RNApp/app/components/Map/Map.js
> +  async makeRequest(countryCode) {
Can you add a docstring / comment for this function? i.e. the input and its format, the return value and its format

2017-01-10 23:06 UTC, rileynwong commented on RNApp/app/components/Map/Map.js
> +        imgUrl ='https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Simple_world_map.svg/2000px-Simple_world_map.svg.png';
Do we have this image? Can we add it to the `berkman/RNApp/app/images/` directory and configure it in `berkman/RNApp/app/config/images.js` ?

2017-01-10 23:06 UTC, rileynwong commented on RNApp/app/routes/MapView/MapView.js
> +// import { makeRequest, getCountryName } from './../../backend/tempBackend';
Since we are using this code, maybe we should rename references to `tempBackend` to something like `apiCaller` or `dataRetriever` something similar?

2017-01-10 23:08 UTC, nancywong commented
Are there prerequisite steps for how to getting the geolocator to work? @nnarang7 

I'm getting this error when I try to navigate to Map View when I run the app:
![image](https://cloud.githubusercontent.com/assets/6015715/21828674/ce2550ec-d75f-11e6-992f-b087619a96ab.png)

2017-01-10 23:09 UTC, nancywong commented on RNApp/app/routes/MapView/MapView.js
> +// import { makeRequest, getCountryName } from './../../backend/tempBackend';
Also -- why is this line commented out? Is it needed to preview the changes? Does this line need to be included in our `master` branch?

2017-01-14 19:59 UTC, sknop8 commented on RNApp/app/routes/MapView/MapView.js
> +// import { makeRequest, getCountryName } from './../../backend/tempBackend';
Oh this line isn't needed (just removed it). At some point I was going to move some of the backend function calls to MapView but in the end decided not to.

2017-01-14 20:38 UTC, merged